var searchData=
[
  ['non_20docker_0',['Traditional Installation (Non-Docker)',['../install_prismspf.html#autotoc_md51',1,'']]],
  ['nonexplicitequationrhs_1',['nonExplicitEquationRHS',['../app_files.html#autotoc_md4',1,'']]],
  ['nonlinear_20solver_20parameters_2',['Note 2: Nonlinear Solver Parameters',['../input_file.html#autotoc_md36',1,'']]],
  ['nonlinear_20solver_20parameters_20for_20each_20nonlinear_20equation_20optional_20see_20note_202_20below_20for_20details_3',['Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)',['../input_file.html#autotoc_md26',1,'']]],
  ['nonlinear_20solver_20parameters_20optional_20see_20note_202_20below_20for_20details_4',['Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)',['../input_file.html#autotoc_md25',1,'']]],
  ['nonlinearsolverparameters_5',['NonlinearSolverParameters',['../classNonlinearSolverParameters.html',1,'']]],
  ['nonuniformdirichletbc_6',['NonUniformDirichletBC',['../classNonUniformDirichletBC.html',1,'']]],
  ['nonuniformdirichletbcvector_7',['NonUniformDirichletBCVector',['../classNonUniformDirichletBCVector.html',1,'']]],
  ['note_201_20below_20for_20details_8',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['note_201_3a_20linear_20solver_20parameters_9',['Note 1: Linear Solver Parameters',['../input_file.html#autotoc_md35',1,'']]],
  ['note_202_20below_20for_20details_10',['note 2 below for details',['../input_file.html#autotoc_md26',1,'Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md25',1,'Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)']]],
  ['note_202_3a_20nonlinear_20solver_20parameters_11',['Note 2: Nonlinear Solver Parameters',['../input_file.html#autotoc_md36',1,'']]],
  ['note_203_20below_20for_20details_12',['Checkpoints (optional, see Note 3 below for details)',['../input_file.html#autotoc_md28',1,'']]],
  ['note_203_3a_20checkpoint_20restart_13',['Note 3: Checkpoint/Restart',['../input_file.html#autotoc_md37',1,'']]],
  ['note_204_20below_20for_20details_14',['Boundary Conditions (see Note 4 below for details)',['../input_file.html#autotoc_md29',1,'']]],
  ['note_204_3a_20boundary_20conditions_15',['Note 4: Boundary Conditions',['../input_file.html#autotoc_md38',1,'']]],
  ['note_205_20below_20for_20details_16',['Loading Initial Conditions from File (optional, see Note 5 below for details)',['../input_file.html#autotoc_md30',1,'']]],
  ['note_205_3a_20loading_20initial_20conditions_20from_20file_17',['Note 5: Loading Initial Conditions from File',['../input_file.html#autotoc_md39',1,'']]],
  ['note_206_20below_20for_20details_18',['note 6 below for details',['../input_file.html#autotoc_md32',1,'Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)'],['../input_file.html#autotoc_md31',1,'Shared Nucleation Parameters (optional, see Note 6 below for details)']]],
  ['note_206_3a_20nucleation_19',['Note 6: Nucleation',['../input_file.html#autotoc_md40',1,'']]],
  ['note_207_20below_20for_20details_20',['Grain Remapping Parameters (optional, see Note 7 below for details)',['../input_file.html#autotoc_md33',1,'']]],
  ['note_207_3a_20grain_20remapping_20parameters_21',['Note 7: Grain Remapping Parameters',['../input_file.html#autotoc_md41',1,'']]],
  ['note_208_20below_20for_20details_22',['Model constants (optional, see Note 8 below for details)',['../input_file.html#autotoc_md34',1,'']]],
  ['note_208_3a_20model_20constants_23',['Note 8: Model Constants',['../input_file.html#autotoc_md42',1,'']]],
  ['note_20on_20types_24',['A note on types',['../app_files.html#autotoc_md3',1,'']]],
  ['nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_25',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['nucleation_26',['Note 6: Nucleation',['../input_file.html#autotoc_md40',1,'']]],
  ['nucleation_20cc_27',['nucleation.cc',['../app_files.html#autotoc_md12',1,'']]],
  ['nucleation_20parameters_20for_20each_20nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_28',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['nucleation_20parameters_20optional_20see_20note_206_20below_20for_20details_29',['Shared Nucleation Parameters (optional, see Note 6 below for details)',['../input_file.html#autotoc_md31',1,'']]],
  ['nucleationparameters_30',['nucleationParameters',['../classnucleationParameters.html',1,'']]],
  ['nucleus_31',['nucleus',['../structnucleus.html',1,'']]],
  ['num_5fquad_5fpoints_32',['num_quad_points',['../classFloodFiller.html#a789d14a23881ab5ce1cf46c362f70614',1,'FloodFiller']]]
];
