var searchData=
[
  ['of_20a_20prisms_20pf_20app_0',['Structure of a PRISMS-PF App',['../app_structure.html',1,'manual']]],
  ['of_20input_20parameters_1',['Tables Describing Each Block of Input Parameters',['../input_file.html#autotoc_md18',1,'']]],
  ['of_20the_20input_20file_2',['General Structure of the Input File',['../input_file.html#autotoc_md17',1,'']]],
  ['of_20the_20prisms_20pf_20user_20guide_3',['Structure of the PRISMS-PF User Guide',['../manual.html#autotoc_md16',1,'']]],
  ['of_20the_20simulation_4',['Visualizing the Results of the Simulation',['../running_apps.html#autotoc_md58',1,'']]],
  ['on_20types_5',['A note on types',['../app_files.html#autotoc_md3',1,'']]],
  ['operator_3d_3d_6',['operator==',['../structboundaryCondition.html#a6d12a25f233e94856c5f258bb190f20f',1,'boundaryCondition']]],
  ['optional_7',['optional',['../input_file.html#autotoc_md22',1,'Mesh Adaptivity (optional)'],['../input_file.html#autotoc_md27',1,'Output (optional)']]],
  ['optional_20see_20note_201_20below_20for_20details_8',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['optional_20see_20note_202_20below_20for_20details_9',['optional see note 2 below for details',['../input_file.html#autotoc_md26',1,'Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md25',1,'Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)']]],
  ['optional_20see_20note_203_20below_20for_20details_10',['Checkpoints (optional, see Note 3 below for details)',['../input_file.html#autotoc_md28',1,'']]],
  ['optional_20see_20note_205_20below_20for_20details_11',['Loading Initial Conditions from File (optional, see Note 5 below for details)',['../input_file.html#autotoc_md30',1,'']]],
  ['optional_20see_20note_206_20below_20for_20details_12',['optional see note 6 below for details',['../input_file.html#autotoc_md32',1,'Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)'],['../input_file.html#autotoc_md31',1,'Shared Nucleation Parameters (optional, see Note 6 below for details)']]],
  ['optional_20see_20note_207_20below_20for_20details_13',['Grain Remapping Parameters (optional, see Note 7 below for details)',['../input_file.html#autotoc_md33',1,'']]],
  ['optional_20see_20note_208_20below_20for_20details_14',['Model constants (optional, see Note 8 below for details)',['../input_file.html#autotoc_md34',1,'']]],
  ['os_20x_15',['Binary Package (Mac OS X)',['../install_prereqs.html#autotoc_md45',1,'']]],
  ['os_20x_20linux_16',['Installing from Source (Mac OS X, Linux)',['../install_prereqs.html#autotoc_md48',1,'']]],
  ['os_20x_20linux_20windows_17',['Docker (Mac OS X, Linux, Windows)',['../install_prereqs.html#autotoc_md47',1,'']]],
  ['other_20app_20files_18',['Other App Files',['../app_files.html',1,'manual']]],
  ['other_20example_20applications_19',['Running the Other Example Applications',['../running_apps.html#autotoc_md59',1,'']]],
  ['output_20optional_20',['Output (optional)',['../input_file.html#autotoc_md27',1,'']]],
  ['outputparameters_21',['outputParameters',['../structoutputParameters.html',1,'']]],
  ['overview_22',['PRISMS-PF Overview',['../manual.html#autotoc_md15',1,'']]]
];
