var searchData=
[
  ['each_20block_20of_20input_20parameters_0',['Tables Describing Each Block of Input Parameters',['../input_file.html#autotoc_md18',1,'']]],
  ['each_20nonlinear_20equation_20optional_20see_20note_202_20below_20for_20details_1',['Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)',['../input_file.html#autotoc_md26',1,'']]],
  ['each_20nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_2',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['each_20time_5findependent_20equation_20optional_20see_20note_201_20below_20for_20details_3',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['el_4',['el',['../classmatrixFreeOperator.html#a413bd8336a4fa1308fa9bd0bdf5f8bcb',1,'matrixFreeOperator']]],
  ['element_20parameters_5',['Element Parameters',['../input_file.html#autotoc_md21',1,'']]],
  ['element_5fvolume_6',['element_volume',['../classelementVolume.html#a55851b1de09ed7f1a2b2573a83446e90',1,'elementVolume']]],
  ['elementvolume_7',['elementvolume',['../classelementVolume.html',1,'elementVolume&lt; dim, degree, number &gt;'],['../classelementVolume.html#a5f797a6c4aee288f40eb27d9c568d6f1',1,'elementVolume::elementVolume()']]],
  ['elementvolume_3c_20dim_2c_20degree_2c_20double_20_3e_8',['elementVolume&lt; dim, degree, double &gt;',['../classelementVolume.html',1,'']]],
  ['equation_20optional_20see_20note_201_20below_20for_20details_9',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['equation_20optional_20see_20note_202_20below_20for_20details_10',['Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)',['../input_file.html#autotoc_md26',1,'']]],
  ['equationlhs_11',['equationLHS',['../app_files.html#autotoc_md5',1,'']]],
  ['equations_20cc_12',['equations.cc',['../app_files.html#autotoc_md0',1,'']]],
  ['eval_5fflag_5fset_5flhs_13',['eval_flag_set_LHS',['../structvariableAttributes.html#a1c93397fe3b1981a863c10d8d3dc43de',1,'variableAttributes']]],
  ['eval_5fflag_5fset_5frhs_14',['eval_flag_set_RHS',['../structvariableAttributes.html#ad3d922b9b150cd37ad75c2b02ed304ba',1,'variableAttributes']]],
  ['eval_5fflags_5fresidual_5flhs_15',['eval_flags_residual_LHS',['../structvariableAttributes.html#afe80efa8a85f08f674291f426dc8e4d7',1,'variableAttributes']]],
  ['eval_5fflags_5fresidual_5frhs_16',['eval_flags_residual_RHS',['../structvariableAttributes.html#a67287df7b6c7f37fa4e6ce68b7869b33',1,'variableAttributes']]],
  ['eval_5flocal_5fdiagonal_17',['eval_local_diagonal',['../classvariableContainer.html#a416f5c5b132d0e922b48d2c3ef2e4f1f',1,'variableContainer']]],
  ['eval_5flocal_5foperator_18',['eval_local_operator',['../classvariableContainer.html#a051e8eaf3cce38c36ecf905cc9a98499',1,'variableContainer::eval_local_operator(const std::function&lt; void(variableContainer &amp;, const dealii::Point&lt; dim, size_type &gt; &amp;)&gt; &amp;func, std::vector&lt; VectorType * &gt; &amp;dst, const std::vector&lt; VectorType * &gt; &amp;src, const std::pair&lt; unsigned int, unsigned int &gt; &amp;cell_range)'],['../classvariableContainer.html#a3956c2a66dea98ff88b973869e9e3533',1,'variableContainer::eval_local_operator(const std::function&lt; void(variableContainer &amp;, const dealii::Point&lt; dim, size_type &gt; &amp;)&gt; &amp;func, VectorType &amp;dst, const std::vector&lt; VectorType * &gt; &amp;src, const std::pair&lt; unsigned int, unsigned int &gt; &amp;cell_range)'],['../classvariableContainer.html#a56f38799b8b1e600fe2612e07be73ebe',1,'variableContainer::eval_local_operator(const std::function&lt; void(variableContainer &amp;, const dealii::Point&lt; dim, size_type &gt; &amp;)&gt; &amp;func, VectorType &amp;dst, const VectorType &amp;src, const std::vector&lt; VectorType * &gt; &amp;src_subset, const std::pair&lt; unsigned int, unsigned int &gt; &amp;cell_range)']]],
  ['example_20app_19',['example app',['../running_apps.html#autotoc_md56',1,'Compiling and Running the Allen-Cahn Example App'],['../running_apps.html',1,'Running a PRISMS-PF Example App']]],
  ['example_20applications_20',['Running the Other Example Applications',['../running_apps.html#autotoc_md59',1,'']]],
  ['example_20apps_21',['The Example Apps',['../running_apps.html#autotoc_md55',1,'']]],
  ['explicitbase_22',['explicitbase',['../classexplicitBase.html#a0598e8eef4d23416c50cbced5db7efad',1,'explicitBase::explicitBase()'],['../classexplicitBase.html',1,'explicitBase&lt; dim, degree &gt;']]],
  ['explicitconstantsolver_23',['explicitconstantsolver',['../classexplicitConstantSolver.html#a620760139cefaaabdc2adbac5d928047',1,'explicitConstantSolver::explicitConstantSolver()'],['../classexplicitConstantSolver.html',1,'explicitConstantSolver&lt; dim, degree &gt;']]],
  ['explicitequationrhs_24',['explicitEquationRHS',['../app_files.html#autotoc_md2',1,'']]],
  ['explicitpostprocesssolver_25',['explicitpostprocesssolver',['../classexplicitPostprocessSolver.html#ad8e777d0c6ce5844ccdd4a69b8a390e1',1,'explicitPostprocessSolver::explicitPostprocessSolver()'],['../classexplicitPostprocessSolver.html',1,'explicitPostprocessSolver&lt; dim, degree &gt;']]],
  ['explicitsolver_26',['explicitsolver',['../classexplicitSolver.html#aa9f1115dfa8385938016d3b1c75d69ea',1,'explicitSolver::explicitSolver()'],['../classexplicitSolver.html',1,'explicitSolver&lt; dim, degree &gt;']]],
  ['export_5ftriangulation_5fas_5fvtk_27',['export_triangulation_as_vtk',['../classtriangulationHandler.html#a5ebb794d89867a3bf852bf2b0f5a3f7a',1,'triangulationHandler']]]
];
