var searchData=
[
  ['of_20a_20prisms_20pf_20app_0',['Structure of a PRISMS-PF App',['../app_structure.html',1,'manual']]],
  ['of_20input_20parameters_1',['Tables Describing Each Block of Input Parameters',['../input_file.html#autotoc_md18',1,'']]],
  ['of_20the_20input_20file_2',['General Structure of the Input File',['../input_file.html#autotoc_md17',1,'']]],
  ['of_20the_20prisms_20pf_20user_20guide_3',['Structure of the PRISMS-PF User Guide',['../manual.html#autotoc_md16',1,'']]],
  ['of_20the_20simulation_4',['Visualizing the Results of the Simulation',['../running_apps.html#autotoc_md58',1,'']]],
  ['old_5forder_5fparameter_5fid_5',['old_order_parameter_id',['../classSimplifiedGrainRepresentation.html#a79444666406510ddc89d8f49eab34202',1,'SimplifiedGrainRepresentation']]],
  ['on_20types_6',['A note on types',['../app_files.html#autotoc_md3',1,'']]],
  ['operator_3c_3c_7',['operator&lt;&lt;',['../classPRISMS_1_1Coordinate.html#a456ffea5294dc3f977c157ca36ab15eb',1,'PRISMS::Coordinate']]],
  ['operator_5b_5d_8',['operator[]',['../classPRISMS_1_1Coordinate.html#af4266297c77bc3ab5f54ac38f89768b6',1,'PRISMS::Coordinate::operator[](int i)'],['../classPRISMS_1_1Coordinate.html#a1958e8c8cfa8dcc55d5aa149ce705990',1,'PRISMS::Coordinate::operator[](int i) const']]],
  ['optional_9',['optional',['../input_file.html#autotoc_md22',1,'Mesh Adaptivity (optional)'],['../input_file.html#autotoc_md27',1,'Output (optional)']]],
  ['optional_20see_20note_201_20below_20for_20details_10',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['optional_20see_20note_202_20below_20for_20details_11',['optional see note 2 below for details',['../input_file.html#autotoc_md26',1,'Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md25',1,'Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)']]],
  ['optional_20see_20note_203_20below_20for_20details_12',['Checkpoints (optional, see Note 3 below for details)',['../input_file.html#autotoc_md28',1,'']]],
  ['optional_20see_20note_205_20below_20for_20details_13',['Loading Initial Conditions from File (optional, see Note 5 below for details)',['../input_file.html#autotoc_md30',1,'']]],
  ['optional_20see_20note_206_20below_20for_20details_14',['optional see note 6 below for details',['../input_file.html#autotoc_md32',1,'Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)'],['../input_file.html#autotoc_md31',1,'Shared Nucleation Parameters (optional, see Note 6 below for details)']]],
  ['optional_20see_20note_207_20below_20for_20details_15',['Grain Remapping Parameters (optional, see Note 7 below for details)',['../input_file.html#autotoc_md33',1,'']]],
  ['optional_20see_20note_208_20below_20for_20details_16',['Model constants (optional, see Note 8 below for details)',['../input_file.html#autotoc_md34',1,'']]],
  ['order_5fparameter_5fid_17',['order_parameter_id',['../classSimplifiedGrainRepresentation.html#a2b9a7c923cb7227a832e807ba4903dbf',1,'SimplifiedGrainRepresentation']]],
  ['orderparameterremapper_18',['OrderParameterRemapper',['../classOrderParameterRemapper.html',1,'']]],
  ['os_20x_19',['Binary Package (Mac OS X)',['../install_prereqs.html#autotoc_md45',1,'']]],
  ['os_20x_20linux_20',['Installing from Source (Mac OS X, Linux)',['../install_prereqs.html#autotoc_md48',1,'']]],
  ['os_20x_20linux_20windows_21',['Docker (Mac OS X, Linux, Windows)',['../install_prereqs.html#autotoc_md47',1,'']]],
  ['other_20app_20files_22',['Other App Files',['../app_files.html',1,'manual']]],
  ['other_20example_20applications_23',['Running the Other Example Applications',['../running_apps.html#autotoc_md59',1,'']]],
  ['output_20optional_24',['Output (optional)',['../input_file.html#autotoc_md27',1,'']]],
  ['overview_25',['PRISMS-PF Overview',['../manual.html#autotoc_md15',1,'']]]
];
