var searchData=
[
  ['package_20linux_0',['Binary Package (Linux)',['../install_prereqs.html#autotoc_md46',1,'']]],
  ['package_20mac_20os_20x_1',['Binary Package (Mac OS X)',['../install_prereqs.html#autotoc_md45',1,'']]],
  ['parallelnucleationlist_2',['parallelNucleationList',['../classparallelNucleationList.html',1,'']]],
  ['parameters_3',['parameters',['../input_file.html#autotoc_md21',1,'Element Parameters'],['../input_file.html#autotoc_md35',1,'Note 1: Linear Solver Parameters'],['../input_file.html#autotoc_md36',1,'Note 2: Nonlinear Solver Parameters'],['../input_file.html#autotoc_md41',1,'Note 7: Grain Remapping Parameters'],['../input_file.html#autotoc_md18',1,'Tables Describing Each Block of Input Parameters']]],
  ['parameters_20for_20each_20nonlinear_20equation_20optional_20see_20note_202_20below_20for_20details_4',['Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)',['../input_file.html#autotoc_md26',1,'']]],
  ['parameters_20for_20each_20nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_5',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['parameters_20for_20each_20time_5findependent_20equation_20optional_20see_20note_201_20below_20for_20details_6',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['parameters_20in_7',['The Input File: parameters.in',['../input_file.html',1,'manual']]],
  ['parameters_20optional_20see_20note_202_20below_20for_20details_8',['Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)',['../input_file.html#autotoc_md25',1,'']]],
  ['parameters_20optional_20see_20note_206_20below_20for_20details_9',['Shared Nucleation Parameters (optional, see Note 6 below for details)',['../input_file.html#autotoc_md31',1,'']]],
  ['parameters_20optional_20see_20note_207_20below_20for_20details_10',['Grain Remapping Parameters (optional, see Note 7 below for details)',['../input_file.html#autotoc_md33',1,'']]],
  ['parse_5fdependencies_11',['parse_dependencies',['../structvariableAttributes.html#a2592218d322f4ef1019ce24a8a26a0d9',1,'variableAttributes']]],
  ['parse_5fline_12',['parse_line',['../classinputFileReader.html#a578f1601441f9c8bb6f3dcda8a918cfb',1,'inputFileReader']]],
  ['parse_5fresidual_5fdependencies_13',['parse_residual_dependencies',['../structvariableAttributes.html#ac6a99e88a8882fa5158d12eee21e2a58',1,'variableAttributes']]],
  ['parsecommandlineopts_14',['ParseCommandLineOpts',['../classParseCommandLineOpts.html',1,'']]],
  ['pcout_15',['pcout',['../classMatrixFreePDE.html#a4c980b65b4311d177998ffae878768bc',1,'MatrixFreePDE']]],
  ['pf_16',['pf',['../install_prismspf.html#autotoc_md52',1,'Downloading PRISMS-PF'],['../install_prismspf.html',1,'Installing PRISMS-PF'],['../index.html#autotoc_md62',1,'What is PRISMS-PF?']]],
  ['pf_20app_17',['Structure of a PRISMS-PF App',['../app_structure.html',1,'manual']]],
  ['pf_20apps_18',['Creating Custom PRISMS-PF Apps',['../custom_apps.html',1,'manual']]],
  ['pf_20example_20app_19',['Running a PRISMS-PF Example App',['../running_apps.html',1,'manual']]],
  ['pf_20overview_20',['PRISMS-PF Overview',['../manual.html#autotoc_md15',1,'']]],
  ['pf_20user_20guide_21',['Structure of the PRISMS-PF User Guide',['../manual.html#autotoc_md16',1,'']]],
  ['pf_20user_20manual_22',['PRISMS-PF User Manual',['../manual.html',1,'']]],
  ['pfield_23',['PField',['../classPRISMS_1_1PField.html',1,'PRISMS']]],
  ['pfuncbase_24',['PFuncBase',['../classPRISMS_1_1PFuncBase.html',1,'PRISMS']]],
  ['pfuncbase_3c_20coordinate_2c_20fieldtype_20_3e_25',['PFuncBase&lt; Coordinate, FieldType &gt;',['../classPRISMS_1_1PFuncBase.html',1,'PRISMS']]],
  ['pfuncbase_3c_20std_3a_3avector_3c_20prisms_3a_3acoordinate_3c_202_20_3e_20_3e_2c_20double_20_3e_26',['PFuncBase&lt; std::vector&lt; PRISMS::Coordinate&lt; 2 &gt; &gt;, double &gt;',['../classPRISMS_1_1PFuncBase.html',1,'PRISMS']]],
  ['pfuncbase_3c_20std_3a_3avector_3c_20prisms_3a_3acoordinate_3c_203_20_3e_20_3e_2c_20double_20_3e_27',['PFuncBase&lt; std::vector&lt; PRISMS::Coordinate&lt; 3 &gt; &gt;, double &gt;',['../classPRISMS_1_1PFuncBase.html',1,'PRISMS']]],
  ['pfuncbase_3c_20std_3a_3avector_3c_20prisms_3a_3acoordinate_3c_20dim_20_3e_20_3e_2c_20double_20_3e_28',['PFuncBase&lt; std::vector&lt; PRISMS::Coordinate&lt; DIM &gt; &gt;, double &gt;',['../classPRISMS_1_1PFuncBase.html',1,'PRISMS']]],
  ['pndarray_29',['PNDArray',['../classPNDArray.html',1,'']]],
  ['pndarray_3c_20std_3a_3avector_3c_20prisms_3a_3ainterpolator_3c_20prisms_3a_3acoordinate_2c_20dim_20_3e_20_2a_20_3e_20_3e_30',['PNDArray&lt; std::vector&lt; PRISMS::Interpolator&lt; PRISMS::Coordinate, dim &gt; * &gt; &gt;',['../classPNDArray.html',1,'']]],
  ['pndarray_3c_20std_3a_3avector_3c_20t_20_3e_20_3e_31',['PNDArray&lt; std::vector&lt; T &gt; &gt;',['../classPNDArray.html',1,'']]],
  ['postprocess_20cc_32',['postprocess.cc',['../app_files.html#autotoc_md9',1,'']]],
  ['postprocessedfields_33',['postProcessedFields',['../app_files.html#autotoc_md11',1,'']]],
  ['prisms_20pf_34',['prisms pf',['../install_prismspf.html#autotoc_md52',1,'Downloading PRISMS-PF'],['../install_prismspf.html',1,'Installing PRISMS-PF'],['../index.html#autotoc_md62',1,'What is PRISMS-PF?']]],
  ['prisms_20pf_20app_35',['Structure of a PRISMS-PF App',['../app_structure.html',1,'manual']]],
  ['prisms_20pf_20apps_36',['Creating Custom PRISMS-PF Apps',['../custom_apps.html',1,'manual']]],
  ['prisms_20pf_20example_20app_37',['Running a PRISMS-PF Example App',['../running_apps.html',1,'manual']]],
  ['prisms_20pf_20overview_38',['PRISMS-PF Overview',['../manual.html#autotoc_md15',1,'']]],
  ['prisms_20pf_20user_20guide_39',['Structure of the PRISMS-PF User Guide',['../manual.html#autotoc_md16',1,'']]],
  ['prisms_20pf_20user_20manual_40',['PRISMS-PF User Manual',['../manual.html',1,'']]],
  ['processors_41',['Running in Release Mode and with Multple Processors',['../running_apps.html#autotoc_md60',1,'']]],
  ['psimplebase_42',['PSimpleBase',['../classPRISMS_1_1PSimpleBase.html',1,'PRISMS']]],
  ['psimplebase_3c_20std_3a_3avector_3c_20prisms_3a_3acoordinate_3c_202_20_3e_20_3e_2c_20double_20_3e_43',['PSimpleBase&lt; std::vector&lt; PRISMS::Coordinate&lt; 2 &gt; &gt;, double &gt;',['../classPRISMS_1_1PSimpleBase.html',1,'PRISMS']]],
  ['psimplebase_3c_20std_3a_3avector_3c_20prisms_3a_3acoordinate_3c_203_20_3e_20_3e_2c_20double_20_3e_44',['PSimpleBase&lt; std::vector&lt; PRISMS::Coordinate&lt; 3 &gt; &gt;, double &gt;',['../classPRISMS_1_1PSimpleBase.html',1,'PRISMS']]]
];
