var searchData=
[
  ['name_0',['name',['../structvariableAttributes.html#a9e5627dd7ee538f84e0a5f18b41a48de',1,'variableAttributes']]],
  ['new_5fsolution_5fset_1',['new_solution_set',['../classsolutionHandler.html#a79c32c2d3de243f3554a87a0964bc2cb',1,'solutionHandler']]],
  ['newton_5fupdate_2',['newton_update',['../classlinearSolverBase.html#a734cf512c88164d6b698946f73ce4ef2',1,'linearSolverBase']]],
  ['newton_5fupdate_5fglobal_5fto_5flocal_5fsolution_3',['newton_update_global_to_local_solution',['../classlinearSolverBase.html#a7dd14a03712ce83a7f196421a7aa82b4',1,'linearSolverBase']]],
  ['newton_5fupdate_5fsrc_4',['newton_update_src',['../classlinearSolverBase.html#a05a9fbfe02b7baaa2f9d7f64e2f09a7a',1,'linearSolverBase']]],
  ['non_20docker_5',['Traditional Installation (Non-Docker)',['../install_prismspf.html#autotoc_md51',1,'']]],
  ['nonexplicitauxiliarysolver_6',['nonexplicitauxiliarysolver',['../classnonexplicitAuxiliarySolver.html',1,'nonexplicitAuxiliarySolver&lt; dim, degree &gt;'],['../classnonexplicitAuxiliarySolver.html#ae804873c2fa96a26f9b374247c9168ec',1,'nonexplicitAuxiliarySolver::nonexplicitAuxiliarySolver()']]],
  ['nonexplicitbase_7',['nonexplicitbase',['../classnonexplicitBase.html',1,'nonexplicitBase&lt; dim, degree &gt;'],['../classnonexplicitBase.html#a4e78526471d5586a469d2af7d00be903',1,'nonexplicitBase::nonexplicitBase()']]],
  ['nonexplicitcononlinearsolver_8',['nonexplicitCoNonlinearSolver',['../classnonexplicitCoNonlinearSolver.html',1,'']]],
  ['nonexplicitequationrhs_9',['nonExplicitEquationRHS',['../app_files.html#autotoc_md4',1,'']]],
  ['nonexplicitlinearsolver_10',['nonexplicitlinearsolver',['../classnonexplicitLinearSolver.html',1,'nonexplicitLinearSolver&lt; dim, degree &gt;'],['../classnonexplicitLinearSolver.html#a17c4cfed3917d17ecac41e79463d7ba5',1,'nonexplicitLinearSolver::nonexplicitLinearSolver()']]],
  ['nonexplicitselfnonlinearsolver_11',['nonexplicitselfnonlinearsolver',['../classnonexplicitSelfNonlinearSolver.html',1,'nonexplicitSelfNonlinearSolver&lt; dim, degree &gt;'],['../classnonexplicitSelfNonlinearSolver.html#abdb63ba5a1abb5c5f7a16f798aa96076',1,'nonexplicitSelfNonlinearSolver::nonexplicitSelfNonlinearSolver()']]],
  ['nonlinear_20solver_20parameters_12',['Note 2: Nonlinear Solver Parameters',['../input_file.html#autotoc_md36',1,'']]],
  ['nonlinear_20solver_20parameters_20for_20each_20nonlinear_20equation_20optional_20see_20note_202_20below_20for_20details_13',['Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)',['../input_file.html#autotoc_md26',1,'']]],
  ['nonlinear_20solver_20parameters_20optional_20see_20note_202_20below_20for_20details_14',['Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)',['../input_file.html#autotoc_md25',1,'']]],
  ['nonlinearsolveparameters_15',['nonlinearSolveParameters',['../structnonlinearSolveParameters.html',1,'']]],
  ['nonlinearsolverparameters_16',['nonlinearSolverParameters',['../classnonlinearSolverParameters.html',1,'']]],
  ['nonuniformdirichlet_17',['nonuniformdirichlet',['../classnonuniformDirichlet.html',1,'nonuniformDirichlet&lt; dim, field_type &gt;'],['../classnonuniformDirichlet.html#ae4e0955ed518e9d37970619830d8bc74',1,'nonuniformDirichlet::nonuniformDirichlet()']]],
  ['note_201_20below_20for_20details_18',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['note_201_3a_20linear_20solver_20parameters_19',['Note 1: Linear Solver Parameters',['../input_file.html#autotoc_md35',1,'']]],
  ['note_202_20below_20for_20details_20',['note 2 below for details',['../input_file.html#autotoc_md26',1,'Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md25',1,'Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)']]],
  ['note_202_3a_20nonlinear_20solver_20parameters_21',['Note 2: Nonlinear Solver Parameters',['../input_file.html#autotoc_md36',1,'']]],
  ['note_203_20below_20for_20details_22',['Checkpoints (optional, see Note 3 below for details)',['../input_file.html#autotoc_md28',1,'']]],
  ['note_203_3a_20checkpoint_20restart_23',['Note 3: Checkpoint/Restart',['../input_file.html#autotoc_md37',1,'']]],
  ['note_204_20below_20for_20details_24',['Boundary Conditions (see Note 4 below for details)',['../input_file.html#autotoc_md29',1,'']]],
  ['note_204_3a_20boundary_20conditions_25',['Note 4: Boundary Conditions',['../input_file.html#autotoc_md38',1,'']]],
  ['note_205_20below_20for_20details_26',['Loading Initial Conditions from File (optional, see Note 5 below for details)',['../input_file.html#autotoc_md30',1,'']]],
  ['note_205_3a_20loading_20initial_20conditions_20from_20file_27',['Note 5: Loading Initial Conditions from File',['../input_file.html#autotoc_md39',1,'']]],
  ['note_206_20below_20for_20details_28',['note 6 below for details',['../input_file.html#autotoc_md32',1,'Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)'],['../input_file.html#autotoc_md31',1,'Shared Nucleation Parameters (optional, see Note 6 below for details)']]],
  ['note_206_3a_20nucleation_29',['Note 6: Nucleation',['../input_file.html#autotoc_md40',1,'']]],
  ['note_207_20below_20for_20details_30',['Grain Remapping Parameters (optional, see Note 7 below for details)',['../input_file.html#autotoc_md33',1,'']]],
  ['note_207_3a_20grain_20remapping_20parameters_31',['Note 7: Grain Remapping Parameters',['../input_file.html#autotoc_md41',1,'']]],
  ['note_208_20below_20for_20details_32',['Model constants (optional, see Note 8 below for details)',['../input_file.html#autotoc_md34',1,'']]],
  ['note_208_3a_20model_20constants_33',['Note 8: Model Constants',['../input_file.html#autotoc_md42',1,'']]],
  ['note_20on_20types_34',['A note on types',['../app_files.html#autotoc_md3',1,'']]],
  ['nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_35',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['nucleation_36',['Note 6: Nucleation',['../input_file.html#autotoc_md40',1,'']]],
  ['nucleation_20cc_37',['nucleation.cc',['../app_files.html#autotoc_md12',1,'']]],
  ['nucleation_20parameters_20for_20each_20nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_38',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['nucleation_20parameters_20optional_20see_20note_206_20below_20for_20details_39',['Shared Nucleation Parameters (optional, see Note 6 below for details)',['../input_file.html#autotoc_md31',1,'']]]
];
