var searchData=
[
  ['name_0',['name',['../structvariableAttributes.html#a9e5627dd7ee538f84e0a5f18b41a48de',1,'variableAttributes']]],
  ['non_20docker_1',['Traditional Installation (Non-Docker)',['../install_prismspf.html#autotoc_md51',1,'']]],
  ['nonexplicitauxiliarysolves_2',['nonexplicitAuxiliarySolves',['../classnonexplicitAuxiliarySolves.html',1,'']]],
  ['nonexplicitcononlinearsolver_3',['nonexplicitCoNonlinearSolver',['../classnonexplicitCoNonlinearSolver.html',1,'']]],
  ['nonexplicitequationrhs_4',['nonExplicitEquationRHS',['../app_files.html#autotoc_md4',1,'']]],
  ['nonexplicitlinearsolver_5',['nonexplicitLinearSolver',['../classnonexplicitLinearSolver.html',1,'']]],
  ['nonexplicitselfnonlinearsolver_6',['nonexplicitSelfNonlinearSolver',['../classnonexplicitSelfNonlinearSolver.html',1,'']]],
  ['nonlinear_20solver_20parameters_7',['Note 2: Nonlinear Solver Parameters',['../input_file.html#autotoc_md36',1,'']]],
  ['nonlinear_20solver_20parameters_20for_20each_20nonlinear_20equation_20optional_20see_20note_202_20below_20for_20details_8',['Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)',['../input_file.html#autotoc_md26',1,'']]],
  ['nonlinear_20solver_20parameters_20optional_20see_20note_202_20below_20for_20details_9',['Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)',['../input_file.html#autotoc_md25',1,'']]],
  ['nonuniformdirichlet_10',['nonuniformdirichlet',['../classnonuniformDirichlet.html#a83e5837c0098eef515ea55d97aacf79a',1,'nonuniformDirichlet::nonuniformDirichlet()'],['../classnonuniformDirichlet.html',1,'nonuniformDirichlet&lt; dim, field_type &gt;']]],
  ['note_201_20below_20for_20details_11',['Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)',['../input_file.html#autotoc_md24',1,'']]],
  ['note_201_3a_20linear_20solver_20parameters_12',['Note 1: Linear Solver Parameters',['../input_file.html#autotoc_md35',1,'']]],
  ['note_202_20below_20for_20details_13',['note 2 below for details',['../input_file.html#autotoc_md26',1,'Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md25',1,'Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)']]],
  ['note_202_3a_20nonlinear_20solver_20parameters_14',['Note 2: Nonlinear Solver Parameters',['../input_file.html#autotoc_md36',1,'']]],
  ['note_203_20below_20for_20details_15',['Checkpoints (optional, see Note 3 below for details)',['../input_file.html#autotoc_md28',1,'']]],
  ['note_203_3a_20checkpoint_20restart_16',['Note 3: Checkpoint/Restart',['../input_file.html#autotoc_md37',1,'']]],
  ['note_204_20below_20for_20details_17',['Boundary Conditions (see Note 4 below for details)',['../input_file.html#autotoc_md29',1,'']]],
  ['note_204_3a_20boundary_20conditions_18',['Note 4: Boundary Conditions',['../input_file.html#autotoc_md38',1,'']]],
  ['note_205_20below_20for_20details_19',['Loading Initial Conditions from File (optional, see Note 5 below for details)',['../input_file.html#autotoc_md30',1,'']]],
  ['note_205_3a_20loading_20initial_20conditions_20from_20file_20',['Note 5: Loading Initial Conditions from File',['../input_file.html#autotoc_md39',1,'']]],
  ['note_206_20below_20for_20details_21',['note 6 below for details',['../input_file.html#autotoc_md32',1,'Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)'],['../input_file.html#autotoc_md31',1,'Shared Nucleation Parameters (optional, see Note 6 below for details)']]],
  ['note_206_3a_20nucleation_22',['Note 6: Nucleation',['../input_file.html#autotoc_md40',1,'']]],
  ['note_207_20below_20for_20details_23',['Grain Remapping Parameters (optional, see Note 7 below for details)',['../input_file.html#autotoc_md33',1,'']]],
  ['note_207_3a_20grain_20remapping_20parameters_24',['Note 7: Grain Remapping Parameters',['../input_file.html#autotoc_md41',1,'']]],
  ['note_208_20below_20for_20details_25',['Model constants (optional, see Note 8 below for details)',['../input_file.html#autotoc_md34',1,'']]],
  ['note_208_3a_20model_20constants_26',['Note 8: Model Constants',['../input_file.html#autotoc_md42',1,'']]],
  ['note_20on_20types_27',['A note on types',['../app_files.html#autotoc_md3',1,'']]],
  ['nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_28',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['nucleation_29',['Note 6: Nucleation',['../input_file.html#autotoc_md40',1,'']]],
  ['nucleation_20cc_30',['nucleation.cc',['../app_files.html#autotoc_md12',1,'']]],
  ['nucleation_20parameters_20for_20each_20nucleating_20variable_20optional_20see_20note_206_20below_20for_20details_31',['Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)',['../input_file.html#autotoc_md32',1,'']]],
  ['nucleation_20parameters_20optional_20see_20note_206_20below_20for_20details_32',['Shared Nucleation Parameters (optional, see Note 6 below for details)',['../input_file.html#autotoc_md31',1,'']]]
];
