var searchData=
[
  ['basesolver_0',['basesolver',['../classbaseSolver.html',1,'baseSolver&lt; dim, degree &gt;'],['../classbaseSolver.html#ae10748bfdfb69cd49b2201e80549f493',1,'baseSolver::baseSolver()']]],
  ['below_20for_20details_1',['below for details',['../input_file.html#autotoc_md29',1,'Boundary Conditions (see Note 4 below for details)'],['../input_file.html#autotoc_md28',1,'Checkpoints (optional, see Note 3 below for details)'],['../input_file.html#autotoc_md33',1,'Grain Remapping Parameters (optional, see Note 7 below for details)'],['../input_file.html#autotoc_md24',1,'Linear Solver Parameters for Each TIME_INDEPENDENT Equation (optional, see Note 1 below for details)'],['../input_file.html#autotoc_md30',1,'Loading Initial Conditions from File (optional, see Note 5 below for details)'],['../input_file.html#autotoc_md34',1,'Model constants (optional, see Note 8 below for details)'],['../input_file.html#autotoc_md26',1,'Nonlinear Solver Parameters for Each Nonlinear Equation (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md32',1,'Nucleation Parameters for Each Nucleating Variable (optional, see Note 6 below for details)'],['../input_file.html#autotoc_md25',1,'Shared Nonlinear Solver Parameters (optional, see Note 2 below for details)'],['../input_file.html#autotoc_md31',1,'Shared Nucleation Parameters (optional, see Note 6 below for details)']]],
  ['binary_20package_20linux_2',['Binary Package (Linux)',['../install_prereqs.html#autotoc_md46',1,'']]],
  ['binary_20package_20mac_20os_20x_3',['Binary Package (Mac OS X)',['../install_prereqs.html#autotoc_md45',1,'']]],
  ['block_20of_20input_20parameters_4',['Tables Describing Each Block of Input Parameters',['../input_file.html#autotoc_md18',1,'']]],
  ['boundary_20conditions_5',['Note 4: Boundary Conditions',['../input_file.html#autotoc_md38',1,'']]],
  ['boundary_20conditions_20see_20note_204_20below_20for_20details_6',['Boundary Conditions (see Note 4 below for details)',['../input_file.html#autotoc_md29',1,'']]],
  ['boundarycondition_7',['boundarycondition',['../classboundaryCondition.html#a21a64fb30bde70bbd7e73a0dbf57dbfc',1,'boundaryCondition::boundaryCondition()'],['../classboundaryCondition.html',1,'boundaryCondition&lt; dim &gt;']]],
  ['boundaryparameters_8',['boundaryparameters',['../classboundaryParameters.html#a0d3e4eb4b5b50779b6c0717ba8a7dc93',1,'boundaryParameters::boundaryParameters()'],['../classboundaryParameters.html',1,'boundaryParameters&lt; dim &gt;']]]
];
