# Site settings
title: PRISMS-PF
email: prisms-pf@umich.edu
description: >-
  An open-source, general purpose framework for high-performance 
  phase field modeling.
baseurl: "/phaseField"
google_analytics: UA—112673248-1

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

# Add the sidebar

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
