# Site settings
title: PRISMS-PF
email: prisms-pf@umich.edu
description: >-
  An open-source, general purpose framework for high-performance 
  phase field modeling.
baseurl: "/phaseField"
google_analytics: UA—112673248-1

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed

