var dir_72d2fbe96e504e5d9d70c5885bd9c513 =
[
    [ "cell_marker_base.h", "cell__marker__base_8h.html", "cell__marker__base_8h" ],
    [ "conditional_ostreams.h", "conditional__ostreams_8h.html", "conditional__ostreams_8h" ],
    [ "constraint_manager.h", "constraint__manager_8h.html", "constraint__manager_8h" ],
    [ "dependencies.h", "dependencies_8h.html", "dependencies_8h" ],
    [ "dependency_extents.h", "dependency__extents_8h.html", "dependency__extents_8h" ],
    [ "dof_manager.h", "dof__manager_8h.html", "dof__manager_8h" ],
    [ "exceptions.h", "exceptions_8h.html", "exceptions_8h" ],
    [ "field_attributes.h", "field__attributes_8h.html", "field__attributes_8h" ],
    [ "field_container.h", "field__container_8h.html", "field__container_8h" ],
    [ "grid_refiner_criterion.h", "grid__refiner__criterion_8h.html", "grid__refiner__criterion_8h" ],
    [ "group_solution_handler.h", "group__solution__handler_8h.html", "group__solution__handler_8h" ],
    [ "initial_conditions.h", "initial__conditions_8h.html", "initial__conditions_8h" ],
    [ "invm_manager.h", "invm__manager_8h.html", "invm__manager_8h" ],
    [ "nonuniform_dirichlet.h", "nonuniform__dirichlet_8h.html", "nonuniform__dirichlet_8h" ],
    [ "parse_cmd_options.h", "parse__cmd__options_8h.html", "parse__cmd__options_8h" ],
    [ "pde_operator_base.h", "pde__operator__base_8h.html", "pde__operator__base_8h" ],
    [ "phase_field_tools.h", "phase__field__tools_8h.html", "phase__field__tools_8h" ],
    [ "problem.h", "problem_8h.html", "problem_8h" ],
    [ "refinement_manager.h", "refinement__manager_8h.html", "refinement__manager_8h" ],
    [ "simulation_timer.h", "simulation__timer_8h.html", "simulation__timer_8h" ],
    [ "solution_indexer.h", "solution__indexer_8h.html", "solution__indexer_8h" ],
    [ "solution_output.h", "solution__output_8h.html", "solution__output_8h" ],
    [ "solve_group.h", "solve__group_8h.html", "solve__group_8h" ],
    [ "system_wide.h", "system__wide_8h.html", "system__wide_8h" ],
    [ "tee_stream.h", "tee__stream_8h.html", "tee__stream_8h" ],
    [ "timer.h", "timer_8h.html", "timer_8h" ],
    [ "triangulation_manager.h", "triangulation__manager_8h.html", "triangulation__manager_8h" ],
    [ "type_enums.h", "type__enums_8h.html", "type__enums_8h" ],
    [ "types.h", "types_8h.html", "types_8h" ]
];