var dir_72d2fbe96e504e5d9d70c5885bd9c513 =
[
    [ "cell_marker_base.h", "cell__marker__base_8h.html", "cell__marker__base_8h" ],
    [ "conditional_ostreams.h", "conditional__ostreams_8h.html", "conditional__ostreams_8h" ],
    [ "constraint_handler.h", "constraint__handler_8h.html", "constraint__handler_8h" ],
    [ "dof_handler.h", "dof__handler_8h.html", "dof__handler_8h" ],
    [ "exceptions.h", "exceptions_8h.html", "exceptions_8h" ],
    [ "grid_refiner.h", "grid__refiner_8h.html", "grid__refiner_8h" ],
    [ "grid_refiner_context.h", "grid__refiner__context_8h.html", "grid__refiner__context_8h" ],
    [ "grid_refiner_criterion.h", "grid__refiner__criterion_8h.html", "grid__refiner__criterion_8h" ],
    [ "initial_conditions.h", "initial__conditions_8h.html", "initial__conditions_8h" ],
    [ "invm_handler.h", "invm__handler_8h.html", "invm__handler_8h" ],
    [ "matrix_free_handler.h", "matrix__free__handler_8h.html", "matrix__free__handler_8h" ],
    [ "matrix_free_operator.h", "matrix__free__operator_8h.html", "matrix__free__operator_8h" ],
    [ "multigrid_info.h", "multigrid__info_8h.html", "multigrid__info_8h" ],
    [ "nonuniform_dirichlet.h", "nonuniform__dirichlet_8h.html", "nonuniform__dirichlet_8h" ],
    [ "parse_cmd_options.h", "parse__cmd__options_8h.html", "parse__cmd__options_8h" ],
    [ "pde_operator.h", "pde__operator_8h.html", "pde__operator_8h" ],
    [ "pde_problem.h", "pde__problem_8h.html", "pde__problem_8h" ],
    [ "phase_field_tools.h", "phase__field__tools_8h.html", "phase__field__tools_8h" ],
    [ "solution_handler.h", "solution__handler_8h.html", "solution__handler_8h" ],
    [ "solution_output.h", "solution__output_8h.html", "solution__output_8h" ],
    [ "solver_handler.h", "solver__handler_8h.html", "solver__handler_8h" ],
    [ "tee_stream.h", "tee__stream_8h.html", "tee__stream_8h" ],
    [ "timer.h", "timer_8h.html", "timer_8h" ],
    [ "triangulation_handler.h", "triangulation__handler_8h.html", "triangulation__handler_8h" ],
    [ "type_enums.h", "type__enums_8h.html", "type__enums_8h" ],
    [ "types.h", "types_8h.html", "types_8h" ],
    [ "variable_attribute_loader.h", "variable__attribute__loader_8h.html", "variable__attribute__loader_8h" ],
    [ "variable_attributes.h", "variable__attributes_8h.html", "variable__attributes_8h" ],
    [ "variable_container.h", "variable__container_8h.html", "variable__container_8h" ],
    [ "vector_mapping.h", "vector__mapping_8h.html", "vector__mapping_8h" ]
];