var searchData=
[
  ['el_0',['el',['../classMatrixFreeOperator.html#aa0c13ef0ab61145e52c3dd37661a51fb',1,'MatrixFreeOperator']]],
  ['elementvolume_1',['elementvolume',['../classElementVolume.html',1,'ElementVolume&lt; dim, degree, number &gt;'],['../classElementVolume.html#abd811dddfdfd404e0a963dad68ca57db',1,'ElementVolume::ElementVolume()']]],
  ['elementvolumecontainer_2',['elementvolumecontainer',['../classElementVolumeContainer.html',1,'ElementVolumeContainer&lt; dim, degree, number &gt;'],['../classElementVolumeContainer.html#a909d6c0504daa16e7025acdb619f3101',1,'ElementVolumeContainer::ElementVolumeContainer()']]],
  ['end_5fsection_3',['end_section',['../classTimer.html#ae1dc504d4bd75188b95693a4951149fd',1,'Timer']]],
  ['eval_5flocal_5fdiagonal_4',['eval_local_diagonal',['../classVariableContainer.html#a71c5237928b80be0b7b4b5d80ce8e872',1,'VariableContainer']]],
  ['eval_5flocal_5foperator_5',['eval_local_operator',['../classVariableContainer.html#ab1049ac9bfb8e56c1a3d57b8b2d71d40',1,'VariableContainer::eval_local_operator(const std::function&lt; void(VariableContainer &amp;, const dealii::Point&lt; dim, SizeType &gt; &amp;, const SizeType &amp;)&gt; &amp;func, std::vector&lt; VectorType * &gt; &amp;dst, const std::vector&lt; VectorType * &gt; &amp;src, const std::pair&lt; unsigned int, unsigned int &gt; &amp;cell_range)'],['../classVariableContainer.html#a44dc814816872019b029765c85fb7df2',1,'VariableContainer::eval_local_operator(const std::function&lt; void(VariableContainer &amp;, const dealii::Point&lt; dim, SizeType &gt; &amp;, const SizeType &amp;)&gt; &amp;func, VectorType &amp;dst, const std::vector&lt; VectorType * &gt; &amp;src, const std::pair&lt; unsigned int, unsigned int &gt; &amp;cell_range)'],['../classVariableContainer.html#a0980ff550f207039f507ca94d3fb02ca',1,'VariableContainer::eval_local_operator(const std::function&lt; void(VariableContainer &amp;, const dealii::Point&lt; dim, SizeType &gt; &amp;, const SizeType &amp;)&gt; &amp;func, VectorType &amp;dst, const VectorType &amp;src, const std::vector&lt; VectorType * &gt; &amp;src_subset, const std::pair&lt; unsigned int, unsigned int &gt; &amp;cell_range)']]],
  ['execute_5fgrid_5frefinement_6',['execute_grid_refinement',['../classTriangulationHandler.html#a31e8d9d80fbc855ad93afb054b038b09',1,'TriangulationHandler']]],
  ['execute_5fsolution_5ftransfer_7',['execute_solution_transfer',['../classSolutionHandler.html#a30edd228edc75cfed767308dcb384ffa',1,'SolutionHandler']]],
  ['export_5ftriangulation_5fas_5fvtk_8',['export_triangulation_as_vtk',['../classTriangulationHandler.html#a964b79030881a41fbe1e314561752c66',1,'TriangulationHandler']]]
];
