var searchData=
[
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classFilteredMatrix_1_1Accessor.html',1,'FilteredMatrix']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classFullMatrix_1_1Accessor.html',1,'FullMatrix']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparseMatrixEZ_1_1const__iterator_1_1Accessor.html',1,'SparseMatrixEZ::const_iterator']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classPETScWrappers_1_1MatrixIterators_1_1const__iterator_1_1Accessor.html',1,'PETScWrappers::MatrixIterators::const_iterator']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparseMatrixIterators_1_1Accessor.html',1,'SparseMatrixIterators']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1SymmetricTensorAccessors_1_1Accessor.html',1,'internal::SymmetricTensorAccessors']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparsityPatternIterators_1_1Accessor.html',1,'SparsityPatternIterators']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classChunkSparseMatrixIterators_1_1Accessor.html',1,'ChunkSparseMatrixIterators']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classPreconditionBlockJacobi_1_1const__iterator_1_1Accessor.html',1,'PreconditionBlockJacobi::const_iterator']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1TableBaseAccessors_1_1Accessor.html',1,'internal::TableBaseAccessors']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classChunkSparsityPatternIterators_1_1Accessor.html',1,'ChunkSparsityPatternIterators']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classTrilinosWrappers_1_1SparseMatrixIterators_1_1Accessor.html',1,'TrilinosWrappers::SparseMatrixIterators']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/singletonBlockMatrixIterators_1_1Accessor.html',1,'BlockMatrixIterators']]],
  ['accessor',['Accessor',['http://www.dealii.org/8.2.1/doxygen/deal.II/classTrilinosWrappers_1_1SparsityPatternIterators_1_1Accessor.html',1,'TrilinosWrappers::SparsityPatternIterators']]],
  ['accessor_3c_20blockmatrix_2c_20false_20_3e',['Accessor&lt; BlockMatrix, false &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classBlockMatrixIterators_1_1Accessor_3_01BlockMatrix_00_01false_01_4.html',1,'BlockMatrixIterators']]],
  ['accessor_3c_20blockmatrix_2c_20true_20_3e',['Accessor&lt; BlockMatrix, true &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classBlockMatrixIterators_1_1Accessor_3_01BlockMatrix_00_01true_01_4.html',1,'BlockMatrixIterators']]],
  ['accessor_3c_20constness_20_3e',['Accessor&lt; Constness &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classTrilinosWrappers_1_1SparseMatrixIterators_1_1Accessor.html',1,'TrilinosWrappers::SparseMatrixIterators']]],
  ['accessor_3c_20false_20_3e',['Accessor&lt; false &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classTrilinosWrappers_1_1SparseMatrixIterators_1_1Accessor_3_01false_01_4.html',1,'TrilinosWrappers::SparseMatrixIterators']]],
  ['accessor_3c_20n_2c_20t_2c_20c_2c_201_20_3e',['Accessor&lt; N, T, C, 1 &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1TableBaseAccessors_1_1Accessor_3_01N_00_01T_00_01C_00_011_01_4.html',1,'internal::TableBaseAccessors']]],
  ['accessor_3c_20number_2c_20false_20_3e',['Accessor&lt; number, false &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparseMatrixIterators_1_1Accessor_3_01number_00_01false_01_4.html',1,'SparseMatrixIterators']]],
  ['accessor_3c_20number_2c_20false_20_3e',['Accessor&lt; number, false &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classChunkSparseMatrixIterators_1_1Accessor_3_01number_00_01false_01_4.html',1,'ChunkSparseMatrixIterators']]],
  ['accessor_3c_20number_2c_20true_20_3e',['Accessor&lt; number, true &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparseMatrixIterators_1_1Accessor_3_01number_00_01true_01_4.html',1,'SparseMatrixIterators']]],
  ['accessor_3c_20number_2c_20true_20_3e',['Accessor&lt; number, true &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classChunkSparseMatrixIterators_1_1Accessor_3_01number_00_01true_01_4.html',1,'ChunkSparseMatrixIterators']]],
  ['accessor_3c_20rank_2c_20dim_2c_20constness_2c_201_2c_20number_20_3e',['Accessor&lt; rank, dim, constness, 1, Number &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1SymmetricTensorAccessors_1_1Accessor_3_01rank_00_01dim_00_01constness_00_011_00_01Number_01_4.html',1,'internal::SymmetricTensorAccessors']]],
  ['accessor_3c_20true_20_3e',['Accessor&lt; true &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classTrilinosWrappers_1_1SparseMatrixIterators_1_1Accessor_3_01true_01_4.html',1,'TrilinosWrappers::SparseMatrixIterators']]],
  ['accessorbase',['AccessorBase',['http://www.dealii.org/8.2.1/doxygen/deal.II/classBlockMatrixIterators_1_1AccessorBase.html',1,'BlockMatrixIterators']]],
  ['accessorbase',['AccessorBase',['http://www.dealii.org/8.2.1/doxygen/deal.II/classTrilinosWrappers_1_1SparseMatrixIterators_1_1AccessorBase.html',1,'TrilinosWrappers::SparseMatrixIterators']]],
  ['accessortypes',['AccessorTypes',['http://www.dealii.org/8.2.1/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1AccessorTypes.html',1,'internal::SymmetricTensorAccessors']]],
  ['accessortypes_3c_20rank_2c_20dim_2c_20false_2c_20number_20_3e',['AccessorTypes&lt; rank, dim, false, Number &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1AccessorTypes_3_01rank_00_01dim_00_01false_00_01Number_01_4.html',1,'internal::SymmetricTensorAccessors']]],
  ['accessortypes_3c_20rank_2c_20dim_2c_20true_2c_20number_20_3e',['AccessorTypes&lt; rank, dim, true, Number &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1AccessorTypes_3_01rank_00_01dim_00_01true_00_01Number_01_4.html',1,'internal::SymmetricTensorAccessors']]],
  ['active',['Active',['http://www.dealii.org/8.2.1/doxygen/deal.II/classIteratorFilters_1_1Active.html',1,'IteratorFilters']]],
  ['activecelliterator',['ActiveCellIterator',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1ActiveCellIterator.html',1,'internal']]],
  ['activecelliterator_3c_20dim_2c_20spacedim_2c_3a_3adofhandler_3c_20dim_2c_20spacedim_20_3e_20_3e',['ActiveCellIterator&lt; dim, spacedim,::DoFHandler&lt; dim, spacedim &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1ActiveCellIterator_3_01dim_00_01spacedim_00_1_1DoFHandler_3_01dim_00_01spacedim_01_4_01_4.html',1,'internal']]],
  ['activecelliterator_3c_20dim_2c_20spacedim_2c_3a_3ahp_3a_3adofhandler_3c_20dim_2c_20spacedim_20_3e_20_3e',['ActiveCellIterator&lt; dim, spacedim,::hp::DoFHandler&lt; dim, spacedim &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1ActiveCellIterator_3_01dim_00_01spacedim_00_1_1hp_1_1DoFHandler_3_01dim_00_01spacedim_01_4_01_4.html',1,'internal']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionILU_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionILU']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionBlockwiseDirect_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionBlockwiseDirect']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionBlockSSOR_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionBlockSSOR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionBlockSOR_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionBlockSOR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionILUT_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionILUT']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionBlockJacobi_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionBlockJacobi']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionBase_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionBase']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverBiCG_1_1AdditionalData.html',1,'PETScWrappers::SolverBiCG']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverBicgstab_1_1AdditionalData.html',1,'PETScWrappers::SolverBicgstab']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionBlockJacobi_1_1AdditionalData.html',1,'PETScWrappers::PreconditionBlockJacobi']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1TransformationSpectrumFolding_1_1AdditionalData.html',1,'SLEPcWrappers::TransformationSpectrumFolding']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1TransformationShiftInvert_1_1AdditionalData.html',1,'SLEPcWrappers::TransformationShiftInvert']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverCG_1_1AdditionalData.html',1,'PETScWrappers::SolverCG']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1TransformationCayley_1_1AdditionalData.html',1,'SLEPcWrappers::TransformationCayley']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverPower_1_1AdditionalData.html',1,'SLEPcWrappers::SolverPower']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverCGS_1_1AdditionalData.html',1,'PETScWrappers::SolverCGS']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverGMRES_1_1AdditionalData.html',1,'TrilinosWrappers::SolverGMRES']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverJacobiDavidson_1_1AdditionalData.html',1,'SLEPcWrappers::SolverJacobiDavidson']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverGeneralizedDavidson_1_1AdditionalData.html',1,'SLEPcWrappers::SolverGeneralizedDavidson']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverArnoldi_1_1AdditionalData.html',1,'SLEPcWrappers::SolverArnoldi']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverChebychev_1_1AdditionalData.html',1,'PETScWrappers::SolverChebychev']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverTFQMR_1_1AdditionalData.html',1,'PETScWrappers::SolverTFQMR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverTCQMR_1_1AdditionalData.html',1,'PETScWrappers::SolverTCQMR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverCR_1_1AdditionalData.html',1,'PETScWrappers::SolverCR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structArpackSolver_1_1AdditionalData.html',1,'ArpackSolver']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverGMRES_1_1AdditionalData.html',1,'PETScWrappers::SolverGMRES']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverLSQR_1_1AdditionalData.html',1,'PETScWrappers::SolverLSQR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structEigenPower_1_1AdditionalData.html',1,'EigenPower']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverPreOnly_1_1AdditionalData.html',1,'PETScWrappers::SolverPreOnly']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SolverRichardson_1_1AdditionalData.html',1,'PETScWrappers::SolverRichardson']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classPreconditionBlock_1_1AdditionalData.html',1,'PreconditionBlock']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPreconditionChebyshev_1_1AdditionalData.html',1,'PreconditionChebyshev']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1SparseDirectMUMPS_1_1AdditionalData.html',1,'PETScWrappers::SparseDirectMUMPS']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionSSOR_1_1AdditionalData.html',1,'PETScWrappers::PreconditionSSOR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionSOR_1_1AdditionalData.html',1,'PETScWrappers::PreconditionSOR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionParaSails_1_1AdditionalData.html',1,'PETScWrappers::PreconditionParaSails']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPreconditionIdentity_1_1AdditionalData.html',1,'PreconditionIdentity']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionLU_1_1AdditionalData.html',1,'PETScWrappers::PreconditionLU']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverTFQMR_1_1AdditionalData.html',1,'TrilinosWrappers::SolverTFQMR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classPreconditionRelaxation_1_1AdditionalData.html',1,'PreconditionRelaxation']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverLanczos_1_1AdditionalData.html',1,'SLEPcWrappers::SolverLanczos']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionEisenstat_1_1AdditionalData.html',1,'PETScWrappers::PreconditionEisenstat']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionBoomerAMG_1_1AdditionalData.html',1,'PETScWrappers::PreconditionBoomerAMG']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverRelaxation_1_1AdditionalData.html',1,'SolverRelaxation']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverBicgstab_1_1AdditionalData.html',1,'TrilinosWrappers::SolverBicgstab']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparseDirectUMFPACK_1_1AdditionalData.html',1,'SparseDirectUMFPACK']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionJacobi_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionJacobi']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classRelaxationBlock_1_1AdditionalData.html',1,'RelaxationBlock']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverLAPACK_1_1AdditionalData.html',1,'SLEPcWrappers::SolverLAPACK']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverMinRes_1_1AdditionalData.html',1,'SolverMinRes']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structMatrixFree_1_1AdditionalData.html',1,'MatrixFree']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverFGMRES_1_1AdditionalData.html',1,'SolverFGMRES']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionAMG_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionAMG']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classPreconditionRichardson_1_1AdditionalData.html',1,'PreconditionRichardson']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structEigenInverse_1_1AdditionalData.html',1,'EigenInverse']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1TransformationShift_1_1AdditionalData.html',1,'SLEPcWrappers::TransformationShift']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverCG_1_1AdditionalData.html',1,'SolverCG']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverBicgstab_1_1AdditionalData.html',1,'SolverBicgstab']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSLEPcWrappers_1_1SolverKrylovSchur_1_1AdditionalData.html',1,'SLEPcWrappers::SolverKrylovSchur']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverGMRES_1_1AdditionalData.html',1,'SolverGMRES']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverCG_1_1AdditionalData.html',1,'TrilinosWrappers::SolverCG']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverQMRS_1_1AdditionalData.html',1,'SolverQMRS']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionChebyshev_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionChebyshev']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionIC_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionIC']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structSolverRichardson_1_1AdditionalData.html',1,'SolverRichardson']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverBase_1_1AdditionalData.html',1,'TrilinosWrappers::SolverBase']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionNone_1_1AdditionalData.html',1,'PETScWrappers::PreconditionNone']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionJacobi_1_1AdditionalData.html',1,'PETScWrappers::PreconditionJacobi']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionILU_1_1AdditionalData.html',1,'PETScWrappers::PreconditionILU']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverCGS_1_1AdditionalData.html',1,'TrilinosWrappers::SolverCGS']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classSparseLUDecomposition_1_1AdditionalData.html',1,'SparseLUDecomposition']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1SolverDirect_1_1AdditionalData.html',1,'TrilinosWrappers::SolverDirect']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionSOR_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionSOR']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structPETScWrappers_1_1PreconditionICC_1_1AdditionalData.html',1,'PETScWrappers::PreconditionICC']]],
  ['additionaldata',['AdditionalData',['http://www.dealii.org/8.2.1/doxygen/deal.II/structTrilinosWrappers_1_1PreconditionSSOR_1_1AdditionalData.html',1,'TrilinosWrappers::PreconditionSSOR']]],
  ['alignedvector',['AlignedVector',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20number_20_3e',['AlignedVector&lt; number &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20point_3c_20dim_2c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e',['AlignedVector&lt; Point&lt; dim, VectorizedArray&lt; Number &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20std_3a_3apair_3c_20tensor_3c_201_2c_20dim_2c_20vectorizedarray_3c_20double_20_3e_20_3e_2c_20vectorizedarray_3c_20double_20_3e_20_3e_20_3e',['AlignedVector&lt; std::pair&lt; Tensor&lt; 1, dim, VectorizedArray&lt; double &gt; &gt;, VectorizedArray&lt; double &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20std_3a_3apair_3c_20tensor_3c_201_2c_20dim_2c_20vectorizedarray_3c_20number_20_3e_20_3e_2c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e',['AlignedVector&lt; std::pair&lt; Tensor&lt; 1, dim, VectorizedArray&lt; Number &gt; &gt;, VectorizedArray&lt; Number &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20std_3a_3apair_3c_20tensor_3c_202_2c_20dim_2c_20vectorizedarray_3c_20double_20_3e_20_3e_2c_20vectorizedarray_3c_20double_20_3e_20_3e_20_3e',['AlignedVector&lt; std::pair&lt; Tensor&lt; 2, dim, VectorizedArray&lt; double &gt; &gt;, VectorizedArray&lt; double &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20std_3a_3apair_3c_20tensor_3c_202_2c_20dim_2c_20vectorizedarray_3c_20number_20_3e_20_3e_2c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e',['AlignedVector&lt; std::pair&lt; Tensor&lt; 2, dim, VectorizedArray&lt; Number &gt; &gt;, VectorizedArray&lt; Number &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20t_20_3e',['AlignedVector&lt; T &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector_3_01T_01_4.html',1,'']]],
  ['alignedvector_3c_20tensor_3c_201_2c_20dim_2c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e',['AlignedVector&lt; Tensor&lt; 1, dim, VectorizedArray&lt; Number &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20tensor_3c_202_2c_20dim_2c_20vectorizedarray_3c_20number_20_3e_20_3e_20_3e',['AlignedVector&lt; Tensor&lt; 2, dim, VectorizedArray&lt; Number &gt; &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvector_3c_20vectorizedarray_3c_20number_20_3e_20_3e',['AlignedVector&lt; VectorizedArray&lt; Number &gt; &gt;',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAlignedVector.html',1,'']]],
  ['alignedvectormove',['AlignedVectorMove',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1AlignedVectorMove.html',1,'internal']]],
  ['alignedvectorset',['AlignedVectorSet',['http://www.dealii.org/8.2.1/doxygen/deal.II/classinternal_1_1AlignedVectorSet.html',1,'internal']]],
  ['allencahnproblem',['AllenCahnProblem',['../class_allen_cahn_problem.html',1,'']]],
  ['anisotropicpolynomials',['AnisotropicPolynomials',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAnisotropicPolynomials.html',1,'']]],
  ['anydata',['AnyData',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAnyData.html',1,'']]],
  ['anything',['Anything',['http://www.dealii.org/8.2.1/doxygen/deal.II/classPatterns_1_1Anything.html',1,'Patterns']]],
  ['arclengthprojectionlinemanifold',['ArclengthProjectionLineManifold',['http://www.dealii.org/8.2.1/doxygen/deal.II/classOpenCASCADE_1_1ArclengthProjectionLineManifold.html',1,'OpenCASCADE']]],
  ['arpacksolver',['ArpackSolver',['http://www.dealii.org/8.2.1/doxygen/deal.II/classArpackSolver.html',1,'']]],
  ['autoderivativefunction',['AutoDerivativeFunction',['http://www.dealii.org/8.2.1/doxygen/deal.II/classAutoDerivativeFunction.html',1,'']]]
];
