var dir_72d2fbe96e504e5d9d70c5885bd9c513 =
[
    [ "cell_marker_base.h", "cell__marker__base_8h_source.html", null ],
    [ "conditional_ostreams.h", "conditional__ostreams_8h_source.html", null ],
    [ "constraint_handler.h", "constraint__handler_8h_source.html", null ],
    [ "dof_handler.h", "dof__handler_8h_source.html", null ],
    [ "exceptions.h", "exceptions_8h_source.html", null ],
    [ "grid_refiner.h", "grid__refiner_8h_source.html", null ],
    [ "grid_refiner_context.h", "grid__refiner__context_8h_source.html", null ],
    [ "grid_refiner_criterion.h", "grid__refiner__criterion_8h_source.html", null ],
    [ "initial_conditions.h", "initial__conditions_8h_source.html", null ],
    [ "invm_handler.h", "invm__handler_8h_source.html", null ],
    [ "matrix_free_handler.h", "matrix__free__handler_8h_source.html", null ],
    [ "matrix_free_operator.h", "matrix__free__operator_8h_source.html", null ],
    [ "multigrid_info.h", "multigrid__info_8h_source.html", null ],
    [ "nonuniform_dirichlet.h", "nonuniform__dirichlet_8h_source.html", null ],
    [ "parse_cmd_options.h", "parse__cmd__options_8h_source.html", null ],
    [ "pde_operator.h", "pde__operator_8h_source.html", null ],
    [ "pde_problem.h", "pde__problem_8h_source.html", null ],
    [ "phase_field_tools.h", "phase__field__tools_8h_source.html", null ],
    [ "solution_handler.h", "solution__handler_8h_source.html", null ],
    [ "solution_output.h", "solution__output_8h_source.html", null ],
    [ "solver_handler.h", "solver__handler_8h_source.html", null ],
    [ "tee_stream.h", "tee__stream_8h_source.html", null ],
    [ "timer.h", "timer_8h_source.html", null ],
    [ "triangulation_handler.h", "triangulation__handler_8h_source.html", null ],
    [ "type_enums.h", "type__enums_8h_source.html", null ],
    [ "types.h", "types_8h_source.html", null ],
    [ "variable_attribute_loader.h", "variable__attribute__loader_8h_source.html", null ],
    [ "variable_attributes.h", "variable__attributes_8h_source.html", null ],
    [ "variable_container.h", "variable__container_8h_source.html", null ],
    [ "vector_mapping.h", "vector__mapping_8h_source.html", null ]
];