var annotated_dup =
[
    [ "PRISMS", null, [
      [ "Body", "classPRISMS_1_1Body.html", "classPRISMS_1_1Body" ],
      [ "Coordinate", "classPRISMS_1_1Coordinate.html", "classPRISMS_1_1Coordinate" ],
      [ "Hexahedron", "classPRISMS_1_1Hexahedron.html", null ],
      [ "Hexahedron_f", "classPRISMS_1_1Hexahedron__f.html", null ],
      [ "HexahedronValues", "classPRISMS_1_1HexahedronValues.html", null ],
      [ "Interpolator", "classPRISMS_1_1Interpolator.html", null ],
      [ "Mesh", "classPRISMS_1_1Mesh.html", null ],
      [ "PField", "classPRISMS_1_1PField.html", null ],
      [ "PFuncBase", "classPRISMS_1_1PFuncBase.html", null ],
      [ "PSimpleBase", "classPRISMS_1_1PSimpleBase.html", null ],
      [ "Quad", "classPRISMS_1_1Quad.html", null ],
      [ "Quad_f", "classPRISMS_1_1Quad__f.html", null ],
      [ "QuadValues", "classPRISMS_1_1QuadValues.html", null ]
    ] ],
    [ "AdaptiveRefinement", "classAdaptiveRefinement.html", "classAdaptiveRefinement" ],
    [ "Bin", "classBin.html", "classBin" ],
    [ "Field", "classField.html", "classField" ],
    [ "FloodFiller", "classFloodFiller.html", "classFloodFiller" ],
    [ "GrainSet", "classGrainSet.html", "classGrainSet" ],
    [ "InitialCondition", "classInitialCondition.html", null ],
    [ "InitialConditionPField", "classInitialConditionPField.html", null ],
    [ "InitialConditionVector", "classInitialConditionVector.html", null ],
    [ "inputFileReader", "classinputFileReader.html", "classinputFileReader" ],
    [ "LinearSolverParameters", "classLinearSolverParameters.html", "classLinearSolverParameters" ],
    [ "MatrixFreePDE", "classMatrixFreePDE.html", "classMatrixFreePDE" ],
    [ "NonlinearSolverParameters", "classNonlinearSolverParameters.html", "classNonlinearSolverParameters" ],
    [ "NonUniformDirichletBC", "classNonUniformDirichletBC.html", null ],
    [ "NonUniformDirichletBCVector", "classNonUniformDirichletBCVector.html", null ],
    [ "nucleationParameters", "classnucleationParameters.html", null ],
    [ "nucleus", "structnucleus.html", null ],
    [ "OrderParameterRemapper", "classOrderParameterRemapper.html", "classOrderParameterRemapper" ],
    [ "parallelNucleationList", "classparallelNucleationList.html", null ],
    [ "ParseCommandLineOpts", "classParseCommandLineOpts.html", null ],
    [ "PNDArray", "classPNDArray.html", null ],
    [ "RefinementCriterion", "classRefinementCriterion.html", null ],
    [ "SimplifiedGrainManipulator", "classSimplifiedGrainManipulator.html", "classSimplifiedGrainManipulator" ],
    [ "SimplifiedGrainRepresentation", "classSimplifiedGrainRepresentation.html", "classSimplifiedGrainRepresentation" ],
    [ "SolverParametersBase", "classSolverParametersBase.html", "classSolverParametersBase" ],
    [ "userInputParameters", "classuserInputParameters.html", "classuserInputParameters" ],
    [ "varBCs", "classvarBCs.html", null ],
    [ "variable_info", "structvariable__info.html", null ],
    [ "variableAttributeLoader", "classvariableAttributeLoader.html", "classvariableAttributeLoader" ],
    [ "variableAttributes", "structvariableAttributes.html", "structvariableAttributes" ],
    [ "variableContainer", "classvariableContainer.html", "classvariableContainer" ],
    [ "variableValueContainer", "classvariableValueContainer.html", null ],
    [ "vectorBCFunction", "classvectorBCFunction.html", null ]
];