name: Publish Doc to GitHub Pages

on:
  push:
    branches:
      - master
      - 4.0-dev

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request'}}

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: landinjm/pagoma-dependencies:alpine-minimal
      options: --user root
    permissions:
      # Write perms to we can copy-paste doxygen docs
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        submodules: true # Check out submodules so we get doxygen awesome

    - name: Install dependencies
      run: |
        apk add --no-cache \
          rsync
          git
          grep
          sed

    - name: Build doxygen files
      run: |
        cmake --workflow --preset docs
        rm -rf build/docs/doc/doxygen

    - name: Update version selector
      run: |
        ./contrib/utilities/update_doc_version_selector.sh build/docs/doc/

    - name: Update default version
      run: |
        ./contrib/utilities/update_doc_default_version.sh build/docs/doc/

    - name: Upload folders
      uses: actions/upload-artifact@v7
      with:
        name: html-doc
        path: build/docs/doc

    - name: Deploy to GitHub pages
      uses: JamesIves/github-pages-deploy-action@v4
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/4.0-dev'
      with:
        branch: gh-pages
        folder: build/docs/doc
        target-folder: doxygen/
        clean: false # This must be false to keep prior versions of the docs
